#!/bin/bash

# create-list: create a list of regular files in a directory

declare -A arr1 origray
declare indexray

#Verify that Parameter is a directory.
if [[ -d "$HOME/$1/" && -n "$1" ]]; then
	echo "Searching for duplicates of files in $1"
else
	echo -e "Usage: delete-dupe Directory | options\nSearches for duplicates of files inside a specified directory and deletes them" >&2
	exit 1
fi

#create list of files in specified directory
for i in $HOME/${1%/}/*; do
	[[ -f $i ]] || continue
	arr1[$i]="$i"
done

#search for all duplicate files in the home directory
#by name
#find checksum of files in specified directory
for i in "${arr1[@]}"; do
	Name=$(sed 's/[][?*]/\\&/g' <<< "$i")

	if [[ $(find ~ -name "${Name##*/}" ! -wholename "$Name") ]]; then
		find ~ -name "${Name##*/}" ! -wholename "$Name" >> temp.txt
		origray[$i]=$(md5sum "$i" | cut -c 1-32)
	fi
done

#create list of duplicate file locations.
if [[ -f temp.txt ]]; then
	mapfile -t indexray < temp.txt
else
	echo "No duplicates were found."
	exit 0
fi

#compare similarly named files by checksum and delete duplicates
count=0
for i in "${!indexray[@]}"; do
	poten=$(md5sum "${indexray[$i]}" | cut -c 1-32)
	for i in "${!origray[@]}"; do
		if [[ "$poten" = "${origray[$i]}" ]]; then
			echo "${indexray[$count]} is a duplicate of a file in $1."
		fi
	done
	count=$((count+1))
done

rm temp.txt