#!/bin/bash

# loan-calc: script to calculate monthyl loan payments

PROGNAME=${0##*/} # Use parameter expansion to get basename

interactive=
usage ()
{
	cat <<- EOF
	Usage: $PROGNAME [PRINCIPAL INTEREST MONTHS | -i]

	Where:

	PRINCIPAL is the amount of the loan.
	INTEREST is the APR as a number (7% = 0.07).
	MONTHS is the length of the loan term.
	Please input non-zero values. Months must be an integer

	EOF
}

if [[ "$1" =~ '-i' ]] || [[ "$1" =~ '--interactive' ]]; then
	interactive=0
	#echo "$interactive"
elif (($# !=3)) || [[ $3 =~ ^[0-9]*\.+[0-9]+$ ]]; then
	usage >&2
	exit 1
elif (($# == 3)); then
	for var in "$@"; do
	if [[ ! "$var" =~ ^[0-9]*\.?[0-9]+$ ]]; then
		usage >&2
		exit 1
	elif [[ "$var" == 0 ]]; then
		 usage >&2
		 exit 1
	fi
	done
fi


if [[ -n "$interactive" ]]; then
	read -p "Enter PRINCIPAL INTEREST MONTHS: " principal interest months
	if [[ ! "$principal" =~ ^[0-9]*\.?[0-9]+$ ]] || [[ ! "$interest" =~ ^[0-9]*\.?[0-9]+$ ]] || [[ ! "$months" =~ ^[0-9]+$ ]]; then
		usage >&2
		exit 1
	fi
	else
		principal=$1
		interest=$2
		months=$3
	fi

bc <<- EOF
	scale = 10
	i = $interest / 12
	p = $principal
	n = $months
	a = p * ((i * ((1+ i) ^ n)) / (((1 + i) ^ n) -1))
	print a, "\n"
EOF
